/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-08-31 19:06:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.revature.dao.WishlistDao;
import com.revature.dao.ProductDao;
import com.revature.entities.Product;
import com.revature.entities.Admin;
import com.revature.entities.Cart;
import com.revature.dao.CartDao;
import com.revature.entities.User;
import java.util.List;
import com.revature.entities.Category;
import com.revature.helper.ConnectionProvider;
import com.revature.dao.CategoryDao;
import com.revature.entities.Message;

public final class viewProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/Components/alert_message.jsp", Long.valueOf(1724998760584L));
    _jspx_dependants.put("/Components/navbar.jsp", Long.valueOf(1725130950352L));
    _jspx_dependants.put("/Components/common_css_js.jsp", Long.valueOf(1724868596744L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(12);
    _jspx_imports_classes.add("com.revature.entities.Message");
    _jspx_imports_classes.add("com.revature.entities.Admin");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.revature.dao.ProductDao");
    _jspx_imports_classes.add("com.revature.dao.WishlistDao");
    _jspx_imports_classes.add("com.revature.entities.Cart");
    _jspx_imports_classes.add("com.revature.entities.Category");
    _jspx_imports_classes.add("com.revature.dao.CategoryDao");
    _jspx_imports_classes.add("com.revature.dao.CartDao");
    _jspx_imports_classes.add("com.revature.entities.Product");
    _jspx_imports_classes.add("com.revature.entities.User");
    _jspx_imports_classes.add("com.revature.helper.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error_exception.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    int productId = Integer.parseInt(request.getParameter("pid"));
    ProductDao productDao = new ProductDao(ConnectionProvider.getConnection());
    Product product = (Product) productDao.getProductsByProductId(productId);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <title>View Product</title>\r\n");
      out.write("    ");
      out.write("<!--CSS-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\" crossorigin=\"anonymous\">\r\n");
      out.write("<!--font awesome-->\r\n");
      out.write("<!--<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/style.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--JavaScript-->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"JS/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--jQuery-->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!--sweet alert-->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        .real-price {\r\n");
      out.write("            font-size: 26px !important;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #027a3e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-price {\r\n");
      out.write("            font-size: 18px !important;\r\n");
      out.write("            text-decoration: line-through;\r\n");
      out.write("            color: #888;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-discount {\r\n");
      out.write("            font-size: 16px !important;\r\n");
      out.write("            color: #ff5722;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .availability {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-lg {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-lg:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .img-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .img-fluid {\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            max-height: 500px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("       .col-md-5\r\n");
      out.write("       {\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("       } \r\n");
      out.write("       \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--navbar -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("activeUser");
Admin admin = (Admin) session.getAttribute("activeAdmin");

CategoryDao catDao = new CategoryDao(ConnectionProvider.getConnection());
List<Category> categoryList = catDao.getAllCategories();
int cartCount = 0; // Initialize cartCount to prevent errors

if (user != null) {
    CartDao cartDao = new CartDao(ConnectionProvider.getConnection());
    cartCount = cartDao.getCartCountByUserId(user.getUserId());
}

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .navbar {\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-link {\r\n");
      out.write("        color: #ffffff !important;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("        font-size: 1.25rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .dropdown-menu {\r\n");
      out.write("        background-color: #343a40 !important;\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("    .dropdown-menu li a {\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("    }\r\n");
      out.write("    .dropdown-menu li a:hover {\r\n");
      out.write("        background-color: #495057 !important;\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-outline-light {\r\n");
      out.write("        border-color: #ffffff;\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-outline-light:hover {\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        color: #343a40;\r\n");
      out.write("    }\r\n");
      out.write("    .navbar-toggler-icon {\r\n");
      out.write("        background-image: url('data:image/svg+xml;charset=utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-menu\" viewBox=\"0 0 24 24\"><path d=\"M3 12h18M3 6h18M3 18h18\"/></svg>');\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-house\"></i>&ensp;RevatureShop\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            ");
 if (admin != null) { 
      out.write("\r\n");
      out.write("                <!-- Admin Nav Bar -->\r\n");
      out.write("                <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-light\" data-bs-toggle=\"modal\" data-bs-target=\"#add-category\">\r\n");
      out.write("                            <i class=\"fa-solid fa-plus fa-xs\"></i>&nbsp;Add Category\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-light\" data-bs-toggle=\"modal\" data-bs-target=\"#add-product\">\r\n");
      out.write("                            <i class=\"fa-solid fa-plus fa-xs\"></i>&nbsp;Add Product\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"admin.jsp\">");
      out.print(admin.getName());
      out.write("</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"LogoutServlet?user=admin\">\r\n");
      out.write("                            <i class=\"fa-solid fa-user-slash\"></i>&nbsp;Logout\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <!-- Guest/All Users Nav Bar -->\r\n");
      out.write("                <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"products.jsp\">Products</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            Category\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"products.jsp?category=0\">All Products</a></li>\r\n");
      out.write("                            ");
 for (Category c : categoryList) { 
      out.write("\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"products.jsp?category=");
      out.print(c.getCategoryId());
      out.write('"');
      out.write('>');
      out.print(c.getCategoryName());
      out.write("</a></li>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <form class=\"d-flex pe-5\" role=\"search\" action=\"products.jsp\" method=\"get\">\r\n");
      out.write("                    <input name=\"search\" class=\"form-control me-2\" type=\"search\" placeholder=\"Search for products\" aria-label=\"Search\">\r\n");
      out.write("                    <button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                ");
 if (user != null) { 
      out.write("\r\n");
      out.write("                    <!-- Logged-in User Nav Bar -->\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                        <li class=\"nav-item pe-3\">\r\n");
      out.write("                            <a class=\"nav-link position-relative\" href=\"cart.jsp\">\r\n");
      out.write("                                <i class=\"fa-solid fa-cart-shopping\"></i>&nbsp;Cart\r\n");
      out.write("                                <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger\">");
      out.print(cartCount);
      out.write("</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item pe-3\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"profile.jsp\">");
      out.print(user.getUserName());
      out.write("</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item pe-3\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"LogoutServlet?user=user\">\r\n");
      out.write("                                <i class=\"fa-solid fa-user-slash\"></i>&nbsp;Logout\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <!-- Guest Nav Bar -->\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                Register\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"register.jsp\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-user-plus\"></i> Register Customer\r\n");
      out.write("                                </a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"seller.jsp\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-user-plus\"></i> Register Seller\r\n");
      out.write("                                </a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                Login\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"login.jsp\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-user-lock\"></i> Login Customer\r\n");
      out.write("                                </a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"sellerlogin.jsp\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-user-lock\"></i> Login Seller\r\n");
      out.write("                                </a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"admin.jsp\">Admin</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');

Message messg = (Message) session.getAttribute("message");
if (messg != null) {

      out.write("\r\n");
      out.write("<div class=\"alert ");
      out.print(messg.getCssClass());
      out.write("\" role=\"alert\" id=\"alert\">\r\n");
      out.write("	");
      out.print(messg.getMessage());
      out.write("\r\n");
      out.write("</div>\r\n");

session.removeAttribute("message");
}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	setTimeout(function() {\r\n");
      out.write("		$('#alert').alert('close');\r\n");
      out.write("	}, 3000);\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-5\">\r\n");
      out.write("                <div class=\"img-container\">\r\n");
      out.write("                    <img src=\"Product_imgs/");
      out.print(product.getProductImages());
      out.write("\" alt=\"Product Image\" class=\"img-fluid\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h2 class=\"mt-3\">");
      out.print(product.getProductName());
      out.write("</h2>\r\n");
      out.write("                    <p class=\"text-muted\"><b>Description:</b> ");
      out.print(product.getProductDescription());
      out.write("</p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        <span class=\"real-price\">&#8377;");
      out.print(product.getProductPriceAfterDiscount());
      out.write("</span>\r\n");
      out.write("                        <span class=\"product-price\">&#8377;");
      out.print(product.getProductPrice());
      out.write("</span>\r\n");
      out.write("                        <span class=\"product-discount\">");
      out.print(product.getProductDiscount());
      out.write(" &#37; off</span>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        <span class=\"availability\">\r\n");
      out.write("                            ");
 if (product.getProductQunatity() > 0) { 
      out.write("\r\n");
      out.write("                                <i class=\"fas fa-check-circle text-success\"></i> Available\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <i class=\"fas fa-times-circle text-danger\"></i> Currently Out of Stock\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p><b>Category:</b> ");
      out.print(catDao.getCategoryName(product.getCategoryId()));
      out.write("</p>\r\n");
      out.write("                    <form method=\"post\">\r\n");
      out.write("                        <div class=\"mt-4 text-center\">\r\n");
      out.write("                            ");
 if (user == null) { 
      out.write("\r\n");
      out.write("                                <button type=\"button\" onclick=\"window.open('login.jsp', '_self')\" class=\"btn btn-primary text-white btn-lg\">\r\n");
      out.write("                                    <i class=\"fas fa-cart-plus\"></i> Add to Cart\r\n");
      out.write("                                </button>\r\n");
      out.write("                                &emsp;\r\n");
      out.write("                                <button type=\"button\" onclick=\"window.open('login.jsp', '_self')\" class=\"btn btn-info text-white btn-lg\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-bag\"></i> Buy Now\r\n");
      out.write("                                </button>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <button type=\"submit\" formaction=\"./AddToCartServlet?uid=");
      out.print(user.getUserId());
      out.write("&pid=");
      out.print(product.getProductId());
      out.write("\" class=\"btn btn-primary text-white btn-lg\">\r\n");
      out.write("                                    <i class=\"fas fa-cart-plus\"></i> Add to Cart\r\n");
      out.write("                                </button>\r\n");
      out.write("                                &emsp;\r\n");
      out.write("                                <a href=\"checkout.jsp\" id=\"buy-btn\" class=\"btn btn-info text-white btn-lg\" role=\"button\" aria-disabled=\"true\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-bag\"></i> Buy Now\r\n");
      out.write("                                </a>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            if ($('#availability').text().trim() == \"Currently Out of stock\") {\r\n");
      out.write("                $('#availability').css('color', 'red');\r\n");
      out.write("                $('.btn').addClass('disabled');\r\n");
      out.write("            }\r\n");
      out.write("            $('#buy-btn').click(function() {\r\n");
      out.write("                ");
 session.setAttribute("pid", productId); session.setAttribute("from", "buy"); 
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
